In [1]:
import numpy as np

In [9]:
# create outer class
class Doctors:
    def __init__(self):
        self.name = 'Doctor'
        self.den = self.Dentist()
        self.car = self.Cardiologist()

    def show(self):
        print('In outer class')
        print('Name:', self.name)

    # create a 1st Inner class
    class Dentist:
        def __init__(self):
            self.name = 'Dr. Savita'
            self.degree = 'BDS'
        def display(self):
            print("Name:", self.name)
            print("Degree:", self.degree)

    # create a 2nd Inner class
    class Cardiologist:
        def __init__(self):
            self.name = 'Dr. Amit'
            self.degree = 'DM'
        def display(self):
            print("Name:", self.name)
            print("Degree:", self.degree)

# create a object
# of outer class
outer = Doctors.Dentist()
outer.display()

# create a object
# of 1st inner class
# d1 = outer.den



Name: Dr. Savita
Degree: BDS


In [14]:
arr = np.array([(2,3,4),(5,6,7)],dtype = complex)
arr

array([[2.+0.j, 3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j, 7.+0.j]])

In [22]:
arr = np.random.randn(4,5)
arr.resize(5,7)
arr

array([[-0.44651677, -0.21707061, -0.067212  ,  0.60849732,  0.28874729,
         0.9576709 , -0.01517389],
       [-0.92564412,  0.0579965 ,  0.97782221, -3.5236124 ,  0.65114779,
        -0.95252107,  1.99061173],
       [-1.12949797, -1.17103895, -0.41619443, -0.28113316, -1.06802555,
         0.22231375,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ]])

In [28]:
arr_1 = np.random.random((2,3))
arr_2 = np.random.random((5,3))
np.vstack((arr_2,arr_1))

array([[0.53974994, 0.41347093, 0.68944336],
       [0.67346566, 0.57520115, 0.23023978],
       [0.25990071, 0.24652311, 0.01632178],
       [0.72274411, 0.75779222, 0.28954648],
       [0.24173306, 0.18928199, 0.95977703],
       [0.3152945 , 0.90907765, 0.48113315],
       [0.04229015, 0.19194606, 0.97064304]])

In [29]:
arr_1 = np.random.random((2,8))
arr_2 = np.random.random((2,4))
np.hstack((arr_2,arr_1))

array([[0.82314404, 0.484799  , 0.49723083, 0.98340964, 0.13703146,
        0.17244359, 0.05060323, 0.78477742, 0.5730696 , 0.37041626,
        0.81517604, 0.59852153],
       [0.34588126, 0.65443554, 0.97907014, 0.12132052, 0.69358684,
        0.63957324, 0.91046169, 0.0534999 , 0.91497678, 0.95732873,
        0.18848934, 0.84488774]])

In [55]:
np.random.seed(45)
a = np.random.random((2,2))
a

array([[0.98901151, 0.54954473],
       [0.2814473 , 0.07728957]])

In [56]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## <h1 style="font-style: italic;color:blue+red"> List vs Numpy arrays

In [73]:
import time
times = time.time()
first_array = range(1000)
second_array = range(1000)
z = [second_array[i]*first_array[i] for i in range(1000)]
second_time = time.time()-times

In [83]:
# numpy array is blazingly faster than python lists

import math
import time
import numpy as np
size_vector = 10000000

def pure_python_version():
    t1=time.time()
    X = range(size_vector)
    Y = range(size_vector)
    Z = [X[i] * Y[i] for i in range(len(X))]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(size_vector)
    Y = np.arange(size_vector)
    Z = X*Y
    return time.time() -t1

t1 = pure_python_version()
t2 = numpy_version()

print(t1, "\t", t2)
print ("Numpy in this example is: " + str(math.floor(t1/t2)) + "x faster")

2.487771987915039 	 0.05485415458679199
Numpy in this example is: 45x faster
